-- 医院后勤工单系统 M0/M1 核心表（MySQL 8.0）
-- 增量脚本：仅创建不存在的表，不覆盖既有业务数据。
-- 业务表只保留逻辑外键，由服务层保证跨表一致性，并为常用关联字段建立索引。

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wo_category (
  id                    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  parent_id             BIGINT       NOT NULL DEFAULT 0 COMMENT '父分类ID，0表示根分类',
  category_code         VARCHAR(32)  NOT NULL COMMENT '分类编码',
  category_name         VARCHAR(64)  NOT NULL COMMENT '分类名称',
  manager_dept_id       BIGINT       NULL COMMENT '默认负责部门ID，逻辑关联sys_dept.dept_id',
  default_sla_rule_id   BIGINT       NULL COMMENT '默认SLA规则ID，逻辑关联wo_sla_rule.id',
  order_num             INT          NOT NULL DEFAULT 0 COMMENT '显示顺序',
  status                CHAR(1)      NOT NULL DEFAULT '0' COMMENT '状态：0正常 1停用',
  create_by             VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '创建者',
  create_time           DATETIME     NULL COMMENT '创建时间',
  update_by             VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
  update_time           DATETIME     NULL COMMENT '更新时间',
  remark                VARCHAR(500) NULL COMMENT '备注',
  del_flag              CHAR(1)      NOT NULL DEFAULT '0' COMMENT '删除标志：0正常 2删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wo_category_code (category_code),
  KEY idx_wo_category_parent (parent_id, status, del_flag),
  KEY idx_wo_category_manager_dept (manager_dept_id, status, del_flag),
  KEY idx_wo_category_default_sla (default_sla_rule_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单业务分类';

CREATE TABLE IF NOT EXISTS wo_sla_rule (
  id                    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '规则ID',
  rule_code             VARCHAR(32)  NOT NULL COMMENT '规则编码',
  rule_name             VARCHAR(64)  NOT NULL COMMENT '规则名称',
  category_id           BIGINT       NULL COMMENT '适用分类ID，空表示全局兜底',
  urgency_level         TINYINT      NOT NULL COMMENT '紧急程度：1一般 2紧急 3特急',
  priority              INT          NOT NULL COMMENT '匹配优先级，数值越大越优先',
  effective_from        DATETIME     NOT NULL COMMENT '生效时间（含）',
  effective_to          DATETIME     NULL COMMENT '失效时间（不含），空表示长期有效',
  response_minutes      INT          NOT NULL COMMENT '接单/响应时限（分钟）',
  arrival_minutes       INT          NULL COMMENT '到场时限（分钟）',
  finish_minutes        INT          NULL COMMENT '完工时限（分钟）',
  reminder_before_min   INT          NOT NULL DEFAULT 15 COMMENT '到期前提醒分钟数',
  allow_extension       CHAR(1)      NOT NULL DEFAULT '1' COMMENT '是否允许延期：0否 1是',
  status                CHAR(1)      NOT NULL DEFAULT '0' COMMENT '状态：0正常 1停用',
  create_by             VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '创建者',
  create_time           DATETIME     NULL COMMENT '创建时间',
  update_by             VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
  update_time           DATETIME     NULL COMMENT '更新时间',
  remark                VARCHAR(500) NULL COMMENT '备注',
  del_flag              CHAR(1)      NOT NULL DEFAULT '0' COMMENT '删除标志：0正常 2删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wo_sla_rule_code (rule_code),
  KEY idx_wo_sla_match (urgency_level, category_id, status, del_flag, priority, effective_from, effective_to),
  KEY idx_wo_sla_category (category_id),
  CONSTRAINT chk_wo_sla_urgency CHECK (urgency_level BETWEEN 1 AND 3),
  CONSTRAINT chk_wo_sla_priority CHECK (priority >= 0),
  CONSTRAINT chk_wo_sla_response CHECK (response_minutes > 0),
  CONSTRAINT chk_wo_sla_arrival CHECK (arrival_minutes IS NULL OR arrival_minutes > 0),
  CONSTRAINT chk_wo_sla_finish CHECK (finish_minutes IS NULL OR finish_minutes > 0),
  CONSTRAINT chk_wo_sla_effective_period CHECK (effective_to IS NULL OR effective_to > effective_from)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单SLA规则';

CREATE TABLE IF NOT EXISTS wo_order (
  id                    BIGINT        NOT NULL AUTO_INCREMENT COMMENT '工单ID',
  order_no              VARCHAR(32)   NOT NULL COMMENT '工单编号',
  title                 VARCHAR(128)  NOT NULL COMMENT '工单标题',
  category_id           BIGINT        NOT NULL COMMENT '分类ID，逻辑关联wo_category.id',
  category_code         VARCHAR(32)   NOT NULL COMMENT '分类编码快照',
  category_name         VARCHAR(64)   NOT NULL COMMENT '分类名称快照',
  source_type           TINYINT       NOT NULL DEFAULT 1 COMMENT '来源：1手机端 2PC端 3接口导入',
  applicant_id          BIGINT        NOT NULL COMMENT '申请人用户ID，逻辑关联sys_user.user_id',
  applicant_name        VARCHAR(64)   NOT NULL COMMENT '申请人姓名快照',
  applicant_phone       VARCHAR(32)   NOT NULL COMMENT '申请人联系电话',
  applicant_dept_id     BIGINT        NULL COMMENT '申请科室ID，逻辑关联sys_dept.dept_id',
  applicant_dept_name   VARCHAR(64)   NULL COMMENT '申请科室名称快照',
  location              VARCHAR(255)  NOT NULL COMMENT '故障位置',
  urgency_level         TINYINT       NOT NULL COMMENT '紧急程度：1一般 2紧急 3特急',
  impact_scope          TINYINT       NOT NULL COMMENT '影响范围：1个人 2科室 3多科室 4全院',
  description           VARCHAR(1000) NOT NULL COMMENT '故障现象描述',
  possible_cause        VARCHAR(1000) NULL COMMENT '可能原因/补充说明',
  status                VARCHAR(32)   NOT NULL COMMENT '业务主状态',
  current_assignee_id   BIGINT        NULL COMMENT '当前维修工程师ID，逻辑关联sys_user.user_id',
  current_assignee_name VARCHAR(64)    NULL COMMENT '当前维修工程师姓名快照',
  sla_rule_id           BIGINT        NULL COMMENT '命中的SLA规则ID，逻辑关联wo_sla_rule.id',
  response_deadline     DATETIME      NULL COMMENT '响应截止时间',
  arrival_deadline      DATETIME      NULL COMMENT '到场截止时间',
  finish_deadline       DATETIME      NULL COMMENT '完工截止时间',
  submitted_at          DATETIME      NULL COMMENT '提交时间',
  assigned_at           DATETIME      NULL COMMENT '最近分派时间',
  accepted_at           DATETIME      NULL COMMENT '接单时间',
  arrived_at            DATETIME      NULL COMMENT '到场时间',
  processing_at         DATETIME      NULL COMMENT '开始处理时间',
  finished_at           DATETIME      NULL COMMENT '工程师提交完工时间',
  confirmed_at          DATETIME      NULL COMMENT '申请人确认时间',
  closed_at             DATETIME      NULL COMMENT '关闭时间',
  overdue_flag          CHAR(1)       NOT NULL DEFAULT '0' COMMENT '是否存在任一SLA超期：0否 1是',
  warning_flag          CHAR(1)       NOT NULL DEFAULT '0' COMMENT '是否处于SLA预警：0否 1是',
  delay_pending_flag    CHAR(1)       NOT NULL DEFAULT '0' COMMENT '是否存在待审批延期：0否 1是',
  response_overdue      CHAR(1)       NOT NULL DEFAULT '0' COMMENT '响应是否超期：0否 1是',
  arrival_overdue       CHAR(1)       NOT NULL DEFAULT '0' COMMENT '到场是否超期：0否 1是',
  finish_overdue        CHAR(1)       NOT NULL DEFAULT '0' COMMENT '完工是否超期：0否 1是',
  extension_deadline    DATETIME      NULL COMMENT '审批后的延期截止时间',
  version               INT           NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by             VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
  create_time           DATETIME      NULL COMMENT '创建时间',
  update_by             VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
  update_time           DATETIME      NULL COMMENT '更新时间',
  remark                VARCHAR(500)  NULL COMMENT '备注',
  del_flag              CHAR(1)       NOT NULL DEFAULT '0' COMMENT '删除标志：0正常 2删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wo_order_no (order_no),
  KEY idx_wo_order_category (category_id, status, create_time),
  KEY idx_wo_order_sla_rule (sla_rule_id),
  KEY idx_wo_order_applicant (applicant_id, status, create_time),
  KEY idx_wo_order_assignee (current_assignee_id, status, create_time),
  KEY idx_wo_order_status (status, urgency_level, create_time),
  KEY idx_wo_order_response_deadline (status, response_overdue, response_deadline),
  KEY idx_wo_order_arrival_deadline (status, arrival_overdue, arrival_deadline),
  KEY idx_wo_order_finish_deadline (status, finish_overdue, finish_deadline),
  KEY idx_wo_order_warning (warning_flag, status, finish_deadline),
  KEY idx_wo_order_dept (applicant_dept_id, create_time),
  CONSTRAINT chk_wo_order_source CHECK (source_type BETWEEN 1 AND 3),
  CONSTRAINT chk_wo_order_urgency CHECK (urgency_level BETWEEN 1 AND 3),
  CONSTRAINT chk_wo_order_impact CHECK (impact_scope BETWEEN 1 AND 4)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单主表';

CREATE TABLE IF NOT EXISTS wo_attachment (
  id                    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  order_id              BIGINT       NULL COMMENT '工单ID，上传暂存时为空，提交后逻辑关联wo_order.id',
  biz_stage             VARCHAR(32)  NOT NULL COMMENT '附件阶段：SUBMIT/ARRIVAL/PROCESS/FINISH/EVALUATION',
  biz_ref_id            BIGINT       NULL COMMENT '关联业务记录ID',
  file_name             VARCHAR(255) NOT NULL COMMENT '原文件名',
  object_key            VARCHAR(512) NOT NULL COMMENT '对象存储键，不对外暴露公开URL',
  storage_provider      VARCHAR(32)  NOT NULL COMMENT '存储提供方：LOCAL/MINIO/OSS/COS等',
  file_hash             VARCHAR(128) NULL COMMENT '文件内容哈希',
  file_type             VARCHAR(128) NULL COMMENT 'MIME类型',
  file_size             BIGINT       NULL COMMENT '文件大小（字节）',
  uploader_id           BIGINT       NOT NULL COMMENT '上传人ID，逻辑关联sys_user.user_id',
  uploader_name         VARCHAR(64)  NULL COMMENT '上传人姓名快照',
  create_time           DATETIME     NOT NULL COMMENT '上传时间',
  del_flag              CHAR(1)      NOT NULL DEFAULT '0' COMMENT '删除标志：0正常 2删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wo_attachment_object_key (object_key),
  KEY idx_wo_attachment_order (order_id, biz_stage, create_time),
  KEY idx_wo_attachment_biz_ref (biz_ref_id),
  KEY idx_wo_attachment_uploader (uploader_id, create_time),
  KEY idx_wo_attachment_hash (file_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单附件';

CREATE TABLE IF NOT EXISTS wo_assignment (
  id                    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '分派记录ID',
  order_id              BIGINT       NOT NULL COMMENT '工单ID，逻辑关联wo_order.id',
  engineer_id           BIGINT       NOT NULL COMMENT '维修工程师ID，逻辑关联sys_user.user_id',
  engineer_name         VARCHAR(64)  NOT NULL COMMENT '维修工程师姓名快照',
  engineer_dept_id      BIGINT       NULL COMMENT '维修部门ID，逻辑关联sys_dept.dept_id',
  assigned_by           BIGINT       NOT NULL COMMENT '分派人ID，逻辑关联sys_user.user_id',
  assigned_by_name      VARCHAR(64)  NOT NULL COMMENT '分派人姓名快照',
  assigned_at           DATETIME     NOT NULL COMMENT '分派时间',
  response_minutes      INT          NOT NULL COMMENT '本次响应时限（分钟）',
  response_deadline     DATETIME     NOT NULL COMMENT '本次响应截止时间',
  assignment_status     VARCHAR(24)  NOT NULL COMMENT 'ACTIVE/ACCEPTED/REASSIGNED/RETURNED/CANCELLED',
  accepted_at           DATETIME     NULL COMMENT '接单时间',
  ended_at              DATETIME     NULL COMMENT '本次分派结束时间',
  return_reason         VARCHAR(500) NULL COMMENT '退回/转派原因',
  create_time           DATETIME     NOT NULL COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_wo_assignment_order (order_id, assigned_at),
  KEY idx_wo_assignment_engineer (engineer_id, assignment_status, assigned_at),
  KEY idx_wo_assignment_engineer_dept (engineer_dept_id, assigned_at),
  KEY idx_wo_assignment_operator (assigned_by, assigned_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单分派历史';

CREATE TABLE IF NOT EXISTS wo_action_log (
  id                    BIGINT        NOT NULL AUTO_INCREMENT COMMENT '操作日志ID',
  order_id              BIGINT        NOT NULL COMMENT '工单ID，逻辑关联wo_order.id',
  action_type           VARCHAR(32)   NOT NULL COMMENT '动作类型',
  from_status           VARCHAR(32)   NULL COMMENT '原状态',
  to_status             VARCHAR(32)   NULL COMMENT '目标状态',
  operator_id           BIGINT        NOT NULL COMMENT '操作人ID，逻辑关联sys_user.user_id',
  operator_name         VARCHAR(64)   NOT NULL COMMENT '操作人姓名快照',
  operator_role         VARCHAR(32)   NOT NULL COMMENT '操作角色快照',
  action_content        VARCHAR(1000) NULL COMMENT '操作说明',
  ext_json              JSON          NULL COMMENT '扩展快照',
  idempotency_key       VARCHAR(64)   NOT NULL COMMENT '动作幂等键',
  action_time           DATETIME      NOT NULL COMMENT '操作时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wo_action_idempotency (operator_id, action_type, idempotency_key),
  KEY idx_wo_action_order (order_id, action_time),
  KEY idx_wo_action_operator (operator_id, action_time),
  KEY idx_wo_action_type (action_type, action_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单流转审计日志';

CREATE TABLE IF NOT EXISTS wo_process_record (
  id                    BIGINT        NOT NULL AUTO_INCREMENT COMMENT '处理记录ID',
  order_id              BIGINT        NOT NULL COMMENT '工单ID，逻辑关联wo_order.id',
  record_stage          VARCHAR(24)   NOT NULL COMMENT 'ARRIVAL/ASSESSMENT/PROGRESS/FINISH',
  engineer_id           BIGINT        NOT NULL COMMENT '工程师ID，逻辑关联sys_user.user_id',
  engineer_name         VARCHAR(64)   NOT NULL COMMENT '工程师姓名快照',
  requires_parts        CHAR(1)       NULL COMMENT '是否需要零部件：0否 1是',
  parts_description     VARCHAR(500)  NULL COMMENT '零部件说明',
  assessed_hours        DECIMAL(8,2)  NULL COMMENT '评估工时',
  assessed_urgency      TINYINT       NULL COMMENT '现场评估紧急程度',
  assessed_scope        TINYINT       NULL COMMENT '现场评估影响范围',
  requires_extension    CHAR(1)       NULL COMMENT '是否需要延期：0否 1是',
  content               VARCHAR(2000) NOT NULL COMMENT '现场说明/处理过程/完工说明',
  occurred_at           DATETIME      NOT NULL COMMENT '业务发生时间',
  create_time           DATETIME      NOT NULL COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_wo_process_order (order_id, record_stage, occurred_at),
  KEY idx_wo_process_engineer (engineer_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='维修处理记录';

CREATE TABLE IF NOT EXISTS wo_evaluation (
  id                    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '评价ID',
  order_id              BIGINT       NOT NULL COMMENT '工单ID，逻辑关联wo_order.id',
  evaluator_id          BIGINT       NOT NULL COMMENT '评价人ID，逻辑关联sys_user.user_id',
  overall_score         TINYINT      NOT NULL COMMENT '总体评分1-5',
  response_score        TINYINT      NULL COMMENT '响应速度评分1-5',
  quality_score         TINYINT      NULL COMMENT '维修质量评分1-5',
  attitude_score        TINYINT      NULL COMMENT '服务态度评分1-5',
  evaluation_content    VARCHAR(500) NULL COMMENT '评价内容',
  evaluated_at          DATETIME     NOT NULL COMMENT '评价时间',
  create_time           DATETIME     NOT NULL COMMENT '创建时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wo_evaluation_order (order_id),
  KEY idx_wo_evaluation_user (evaluator_id, evaluated_at),
  CONSTRAINT chk_wo_evaluation_overall CHECK (overall_score BETWEEN 1 AND 5),
  CONSTRAINT chk_wo_evaluation_response CHECK (response_score IS NULL OR response_score BETWEEN 1 AND 5),
  CONSTRAINT chk_wo_evaluation_quality CHECK (quality_score IS NULL OR quality_score BETWEEN 1 AND 5),
  CONSTRAINT chk_wo_evaluation_attitude CHECK (attitude_score IS NULL OR attitude_score BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单服务评价';

CREATE TABLE IF NOT EXISTS wo_engineer_status (
  id                    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '状态记录ID',
  engineer_id           BIGINT       NOT NULL COMMENT '工程师用户ID，逻辑关联sys_user.user_id',
  engineer_name         VARCHAR(64)  NOT NULL COMMENT '工程师姓名快照',
  engineer_dept_id      BIGINT       NULL COMMENT '所属维修部门，逻辑关联sys_dept.dept_id',
  duty_status           VARCHAR(16)  NOT NULL COMMENT '值班状态：OFF_DUTY/ON_DUTY',
  work_status           VARCHAR(16)  NOT NULL COMMENT '工作状态：AVAILABLE/WORKING/BUSY',
  current_order_id      BIGINT       NULL COMMENT '当前主工单ID，逻辑关联wo_order.id',
  active_order_count    INT          NOT NULL DEFAULT 0 COMMENT '进行中工单数',
  overdue_order_count   INT          NOT NULL DEFAULT 0 COMMENT '超期工单数',
  status_source         VARCHAR(16)  NOT NULL DEFAULT 'AUTO' COMMENT '状态来源：AUTO/MANUAL',
  last_changed_at       DATETIME     NOT NULL COMMENT '最近状态变化时间',
  last_heartbeat_at     DATETIME     NULL COMMENT '客户端最近心跳时间，空表示从未上报',
  update_time           DATETIME     NOT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wo_engineer_status_user (engineer_id),
  KEY idx_wo_engineer_status (duty_status, work_status, overdue_order_count),
  KEY idx_wo_engineer_dept (engineer_dept_id, duty_status, work_status),
  KEY idx_wo_engineer_current_order (current_order_id),
  KEY idx_wo_engineer_heartbeat (last_heartbeat_at),
  CONSTRAINT chk_wo_engineer_active_count CHECK (active_order_count >= 0),
  CONSTRAINT chk_wo_engineer_overdue_count CHECK (overdue_order_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='维修工程师状态快照';
